endpoint_url: "127.0.0.1:8080"
access_key: "foo"
secret_key: "bar"
disable_ssl: True
cds_buckets: 
  - "cds_foo"
  - "cds_bar"
trigger_buckets:
  - "triggers01_foo"
  - "triggers02_bar"
timezone: "Europe/Moscow"
